export const UPDATE_TEXT_INPUT = 'UPDATE_TEXT_INPUT';
export const FETCH_REPOS_REQUEST = 'FETCH_REPOS_REQUEST';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_ERROR = 'FETCH_REPOS_ERROR';
export const FETCH_README_REQUEST = 'FETCH_README_REQUEST';
export const FETCH_README_SUCCESS = 'FETCH_README_SUCCESS';
export const FETCH_README_ERROR = 'FETCH_README_ERROR';